// <copyright file="TestConfiguration.cs" company="Metlife">
//  Copyright (c) Metlife. All rights reserved.
// </copyright>
// <summary>TestConfiguration.cs class Test Configuration settings.</summary>
// <auto-generated />
namespace INF.CodedUI.TestAutomation.Entities
{
    using System.Collections;

    public class TestConfiguration : CollectionBase
    {
        public string StepNo { get; set; }

        public string DataType { get; set; }

        public string VariableName { get; set; }

        public string TestData { get; set; }
    }
}