// <copyright file="UIControl.cs" company="Metlife">
//  Copyright (c) Metlife. All rights reserved.
// </copyright>
// <summary>UIControl.cs class handles User interface control data.</summary>
// <auto-generated />
namespace INF.CodedUI.TestAutomation.Entities
{
    using System.Collections;

    public class UiControl : CollectionBase
    {
        public string UiControlId { get; set; }

        public string UiTitle { get; set; }

        public string UiType { get; set; }

        public string UiControlType { get; set; }

        public string UiControlSearchProperty { get; set; }

        public string UiControlSearchValue { get; set; }

        public string UiControlFilterProperty { get; set; }

        public string UiControlFilterValue { get; set; }
    }
}