// <copyright file="Verification.cs" company="Metlife">
//  Copyright (c) Metlife. All rights reserved.
// </copyright>
// <summary>Verification.cs class handles Verifications data.</summary>
// <auto-generated />
namespace INF.CodedUI.TestAutomation.Entities
{
    using System.Collections;

    public class Verification : CollectionBase
    {
        public string VerificationId { get; set; }

        public string VerificationType { get; set; }

        public string OperatorToUse { get; set; }

        public string UiControlProperty { get; set; }

        public string DatabaseQuery { get; set; }

        public string DatabaseServer { get; set; }

        public string DatabaseName { get; set; }
    }
}